Code style everywhere
deephaven/deephaven-core pull request #1078
Opened 2021-08-17 17:20 UTC by devinrsmith

Fixes #924

2021-08-17 17:26 UTC, devinrsmith commented
Note: we should *not* squash merge this. After review, we should squash into two commits: the gradle logic changes, and then the style applied everywhere. This way, any outstanding branches that have merge conflicts have an easy path for resolution: cherry-pick the gradle logic changes and run style locally.

2021-08-17 22:06 UTC, jcferretti approved these changes
I did not look at every file (not realistic IMHO).  We discussed about process and such over slack.

2021-08-24 19:33 UTC, jcferretti approved these changes

2021-08-24 20:08 UTC, chipkent requested changes

2021-08-24 20:08 UTC, chipkent commented on CONTRIBUTING.md
> +The [styleguide](style/README.md) is applied globally, except for cases of check-in code generation.
The [styleguide](style/README.md) is applied globally, to the entire project, except for generated code that gets checked in.

2021-08-24 20:10 UTC, chipkent approved these changes

2021-08-24 20:11 UTC, merged