Demo refactor updates
deephaven/deephaven-core pull request #1658
Opened 2021-12-08 19:47 UTC by jjbrosnan

Ryan's refactor left code blocks in the demo notebooks that is broken.  This fixes that.

2021-12-08 22:37 UTC, chipkent requested changes

2021-12-08 22:37 UTC, chipkent commented on demo/web/src/main/notebooks/01 Tables, Updates, and the Engine.md
> +from deephaven import Aggregation.combo_agg as combo_agg
```suggestion
from deephaven import Aggregation as agg, combo_agg
```

2021-12-08 22:37 UTC, chipkent commented on demo/web/src/main/notebooks/02 Stream and Batch Together.md
> +trades_batch_view = csv.read("/data/large/crypto/CryptoTrades_20210922.csv")
```suggestion
from deephaven import read_csv
trades_batch_view = read_csv("/data/large/crypto/CryptoTrades_20210922.csv")
```
We are defaulting to this syntax until we document the CSV module in v2.

2021-12-09 14:51 UTC, pete-petey commented
I have read the CLA Document and I hereby sign the CLA.

2021-12-09 21:33 UTC, chipkent approved these changes

2021-12-13 17:01 UTC, merged