Add deephaven.learn/NumPy notebook for live demo
deephaven/deephaven-core pull request #1832
Opened 2022-01-14 16:14 UTC by jjbrosnan

This notebook uses deephaven.learn and NumPy to show a prospective user how they work in Deephaven.

2022-02-02 16:30 UTC, margaretkennedy commented on demo/web/src/main/notebooks/Python_AI/00 Deephaven with PyTorch.md
> +# Deephaven with PyTorch
B. Data science, ML, & AI "B4 PyTorch and Deephaven"

2022-02-02 16:39 UTC, margaretkennedy commented on demo/web/src/main/notebooks/Python_AI/01 Deephaven with SciKit-Learn.md
> +# Deephaven with SciKit-Learn
B. Data science, ML, & AI / B5 "B5 ScikitLearn and Deephaven"

2022-02-02 16:40 UTC, margaretkennedy commented on demo/web/src/main/notebooks/Python_AI/02 Deephaven with TensorFlow.md
> +# Deephaven with TensorFlow
B. Data science, ML, & AI "B3 TensorFlow and Deephaven"

2022-02-02 16:40 UTC, margaretkennedy requested changes
Just file names

2022-02-03 23:41 UTC, jjbrosnan commented
This PR is being closed for a newer one with less differences in file structure:

[Numba + NumPy](https://github.com/deephaven/deephaven-core/pull/1934).

2022-02-03 23:41 UTC, closed without merging