Quality of life improvements for formula handling around BigDecimal columns.
deephaven/deephaven-core pull request #1899
Opened 2022-01-27 22:11 UTC by jcferretti

![Deephaven - Google Chrome_143](https://user-images.githubusercontent.com/37232625/151452198-5bcce9a1-7f0a-45b6-a817-3fca2346b538.png)

2022-01-27 22:29 UTC, cpwright requested changes
This all needs unit test coverage; we can't just merge it unless we are sure that we cover all these cases from an update or where statement.

2022-01-27 22:29 UTC, cpwright commented on engine/table/src/main/java/io/deephaven/engine/table/impl/lang/QueryLanguageFunctionUtils.java
> +        if (a == QueryConstants.NULL_LONG || b == null) {
should you really repeat checks if you are just going to use the commutative operator?

2022-01-27 22:29 UTC, cpwright commented on engine/table/src/main/java/io/deephaven/engine/table/impl/lang/QueryLanguageFunctionUtils.java
> +        if (a == QueryConstants.NULL_DOUBLE) {
Deephaven normally has special comparisons for Double.NaN.

2022-01-28 01:59 UTC, cpwright reviewed
So I think you did a good job covering the functions.  There is a question as to whether it makes sense to verify a few uses in a formula.  I know you have it in the demo, but a handful of unit tests (less exhaustive) is still probably worth it to ensure we don't break e.g. the parser's handling of these things.

2022-01-28 12:01 UTC, cpwright submitted a review, later dismissed

2022-01-28 19:42 UTC, cpwright approved these changes

2022-01-28 20:21 UTC, merged

2022-01-29 01:14 UTC, jcferretti commented
Part of #1753