Update demo notebooks to v2 syntax
deephaven/deephaven-core pull request #2236
Opened 2022-04-08 20:23 UTC by jjbrosnan

All notebooks have V2 syntax with the exception of:

`02 Steam and Batch Together.md`

That notebook is awating Python wrappers for `formatColumns` and `formatColumnWhere`.  Once those are in main, the notebook will be updated and this will be ready for a merge.

2022-04-08 21:11 UTC, jakemulf requested changes
Small syntax updates, there's more for me to go through but I'll finish the review later

2022-04-08 21:11 UTC, jakemulf commented on demo/web/src/main/notebooks/08 Table Listeners.md
> +table = time_table('00:00:02').update(["Number = (int)(byte)random.randint(1,100)"])
```suggestion
table = time_table('00:00:02').update(["Number = (int)random.randint(1,100)"])
```

2022-04-08 21:11 UTC, jakemulf commented on demo/web/src/main/notebooks/08 Table Listeners.md
> +table_two = time_table('00:00:05').update(["Number = (int)(byte)random.randint(1,100)"])
```suggestion
table_one = time_table('00:00:02').update(["Number = (int)random.randint(1,100)"])
table_two = time_table('00:00:05').update(["Number = (int)random.randint(1,100)"])
```

2022-04-08 21:11 UTC, jakemulf commented on demo/web/src/main/notebooks/A. Real-time table ops/A1 Create tables and fake data.md
> +    return table.update(formulas=["Number = (int)(byte)random_int()", "Character = (String)random_character()", "Boolean = (boolean)random_boolean()"])
```suggestion
    return table.update(formulas=["Number = (int)random_int()", "Character = (String)random_character()", "Boolean = (boolean)random_boolean()"])
```

2022-04-12 15:13 UTC, hythloda approved these changes

2022-04-13 18:02 UTC, merged