Improve BigInteger handling in Parquet files (Closes #3125)
deephaven/deephaven-core pull request #3126
Opened 2022-11-30 18:38 UTC by abaranec

BigIntegers can be encoded as DecimalLogicalType with a precision of 1 and scale of 0 using a variant of BigDecimalParquetBytesCodec.

2022-11-30 21:44 UTC, jcferretti submitted a review, later dismissed

2022-11-30 22:07 UTC, rcaudy reviewed
I didn't really review this, just glanced at the shape of the work.

2022-11-30 22:07 UTC, rcaudy commented on engine/table/src/main/java/io/deephaven/engine/table/impl/CodecLookup.java
> +                dataType == BigInteger.class;
You might need/want to add a comment here like the one for `BigDecimal`.

2022-12-02 01:55 UTC, jcferretti requested changes

2022-12-02 01:55 UTC, jcferretti commented on extensions/parquet/table/src/main/java/io/deephaven/parquet/table/ParquetSchemaReader.java
> +                if (decimalLogicalType.getPrecision() == 1 && decimalLogicalType.getScale() == 0) {
Can we add a comment here that the 1 is a "marker" value that we ourselves set up before?
An unsuspecting reader (me, in the past, before getting an explanation) may ask themselves "why is it that the precision would be exactly 1?"

2022-12-02 01:55 UTC, jcferretti commented on engine/table/src/main/java/io/deephaven/engine/util/BigDecimalUtils.java
> -        try (final ChunkSource.GetContext context = source.makeGetContext(sz);
Can we modify the block comment right before this point to make it explicit that we are not reading the whole table, just making an estimate based on the first PRECISION_SCALE_N_TO_INSPECT values?

2022-12-02 18:42 UTC, jcferretti requested changes

2022-12-02 18:42 UTC, jcferretti commented on engine/table/src/main/java/io/deephaven/engine/util/BigDecimalUtils.java
>          try (final ChunkSource.GetContext context = source.makeGetContext(PRECISION_SCALE_N_TO_INSPECT);
Rename PRECISION_SCALE_N_TO_INSPECT ?





[1:41](https://illumon.slack.com/archives/C04DJDAM0CT/p1670006500747539)
Now is more of a working buffer size than a limit

2022-12-02 18:52 UTC, jcferretti approved these changes

2022-12-02 19:04 UTC, jcferretti approved these changes

2022-12-02 20:05 UTC, merged