Add /apps/libs/* to the classpath
deephaven/deephaven-core pull request #3308
Opened 2023-01-14 01:25 UTC by rbasralian

Add `/apps/libs/*` to the classpath of the server image, so that the [documentation](https://deephaven.io/core/groovy/docs/how-to-guides/install-java-packages/) matches reality.

2023-01-17 18:17 UTC, devinrsmith commented
Note: we don't have "custom extended classpath" support anymore, at least out of the box with our existing docker images. It would be relatively easy to add back in; and we'd want to explicitly mention it as part of https://deephaven.io/core/docs/how-to-guides/configuration/native-application/.

2023-01-17 18:20 UTC, devinrsmith commented
Instead of naming a specific directory, I'd suggest using an environment variable `EXTRA_CLASSPATH`, or something like that, as it would better fit in with the nature of how we use environment variables wrt the start script.

2023-01-17 18:25 UTC, devinrsmith requested changes
Ah - I thought this was an "issue" at first.

I think we can merge something like this in. But I think it's best to use an optional environment variable "EXTRA_CLASSPATH" if set (otherwhise empty) or something like that.

There's also a little blurb of DH specific documentation in this file, we should mention that we are adding the ability to change the classpath.

2023-01-17 18:28 UTC, devinrsmith commented
I _think_ it makes sense to prepend the extra classpath (as your PR suggests) instead of appending the extra classpath - but it's a worthwhile point of potential discussion.

2023-01-19 18:26 UTC, rbasralian commented
> I _think_ it makes sense to prepend the extra classpath (as your PR suggests) instead of appending the extra classpath - but it's a worthwhile point of potential discussion.

I definitely think prepending is better. It lets you do some risky stuff (e.g. replacing our dependencies), but that is better than _not_ letting someone do that when they want to. (It's also in line with how DHE works, and we've never contemplated changing it there.)


I did change it to take an `EXTRA_CLASSPATHS` environment variable, but kept `/apps/libs/*` as the default, since our documentation already claims that it works, and there's no harm in having a useful default.

2023-01-24 16:48 UTC, devinrsmith commented
I think it's best to not have a default, and instead update the documentation to reflect the extra environment variable as necessary if you want to extend the classpath. (As a better follow-up, I think we need new documentation around how to do this "properly": https://github.com/deephaven/deephaven.io/issues/2091.)

I also think we shouldn't be printing anything out in this script.

2023-01-24 16:57 UTC, devinrsmith commented
I also mentioned in DM, but the start script is for *native* users too, not just docker. In which case, I think setting a default at the script level is inappropriate; but we _can_ set a default higher up in the docker image layers.

2023-01-24 20:22 UTC, devinrsmith requested changes

2023-01-24 20:22 UTC, devinrsmith commented on buildSrc/src/main/resources/unixStartScript.txt
> +fi
A bit nit-picky, but can you add this comment and try this combined version with your test setup? (I've verified to it seems to work for me.) `$classpath` is potentially the majority of the script length and if we can do without doubling it that would be good.

```shell
# Deephaven edit.
# Prepend EXTRA_CLASSPATH and colon if EXTRA_CLASSPATH is non-empty.
CLASSPATH=\${EXTRA_CLASSPATH:+\$EXTRA_CLASSPATH:}$classpath
```

2023-01-25 17:58 UTC, devinrsmith approved these changes
Please change your commit message to explain `EXTRA_CLASSPATH` - the `/apps/libs/*` is incidental in this case; the `/apps/libs/*` message will be on the deephaven-server-docker side of things.

2023-01-27 16:44 UTC, merged

2023-01-27 16:45 UTC, deephaven-internal commented
Labels indicate documentation is required. Issues for documentation have been opened:

How-to: https://github.com/deephaven/deephaven.io/issues/2103
Conceptual: https://github.com/deephaven/deephaven.io/issues/2101
Reference: https://github.com/deephaven/deephaven.io/issues/2102
Blog: https://github.com/deephaven/deephaven.io/issues/2100