Wrap OuterJoinTools in Python
deephaven/deephaven-core pull request #3370
Opened 2023-01-27 02:01 UTC by jmao-denver

Fixes #3340

Found a bug reported in #3369

2023-01-30 19:01 UTC, chipkent requested changes

2023-01-31 04:10 UTC, jmao-denver commented on py/server/deephaven/outer_joins.py
> +#
Moving the module to experimental which this functionality the best in its current shape and form.

2023-01-31 16:01 UTC, jmao-denver commented on py/server/deephaven/outer_joins.py
> +        raise DHError(e, message="failed to perform full-outer-join on tables.") from e
that's intentional because it is not a table operation by definition.

2023-01-31 16:01 UTC, jmao-denver commented on py/server/deephaven/outer_joins.py
> +        raise DHError(e, message="failed to perform left-outer-join on tables.") from e
same response.

2023-01-31 16:07 UTC, jmao-denver commented on py/server/deephaven/outer_joins.py
> +def full_outer_join(table1: Table, table2: Table, on: Union[str, Sequence[str]],
I think either is fine but generally I prefer to map the wrapper to the Java code as closely as possible.

2023-02-01 16:06 UTC, chipkent approved these changes

2023-02-01 16:22 UTC, merged

2023-02-01 16:23 UTC, deephaven-internal commented
Labels indicate documentation is required. Issues for documentation have been opened:

How-to: https://github.com/deephaven/deephaven.io/issues/2131
Conceptual: https://github.com/deephaven/deephaven.io/issues/2133
Reference: https://github.com/deephaven/deephaven.io/issues/2132
Blog: https://github.com/deephaven/deephaven.io/issues/2130