Correctly handle None input value for primitive type columns in new_table()
deephaven/deephaven-core pull request #3729
Opened 2023-04-24 18:37 UTC by jmao-denver

2023-04-24 18:46 UTC, devinrsmith reviewed
Awesome!

2023-04-24 20:35 UTC, jmao-denver commented on py/server/deephaven/dtypes.py
> +def null_remap(dtype: DType) -> Callable[[Any], Any]:
It is correct. The first value to Callable definition is the argument list.

2023-04-25 14:57 UTC, chipkent requested changes

2023-04-26 16:44 UTC, chipkent approved these changes

2023-04-26 16:48 UTC, merged