Add onFlushCallback to TablePublisher
deephaven/deephaven-core pull request #4286
Opened 2023-08-08 16:39 UTC by devinrsmith

Follow-up to #4220

2023-08-08 19:09 UTC, chipkent requested changes

2023-08-08 20:48 UTC, chipkent submitted a review, later dismissed

2023-08-09 18:09 UTC, chipkent approved these changes

2023-08-09 18:39 UTC, rcaudy commented on engine/table/src/main/java/io/deephaven/stream/StreamToBlinkTableAdapter.java
> +    public void initialize() {
It needs to be public if the new constructor is, and I think that that is a valuable tool to offer.
It needs to be idempotent, or error on re-invocation.

2023-08-09 19:13 UTC, chipkent approved these changes

2023-08-09 19:52 UTC, merged