Move the C++ client to shared libraries; reorganize its dir structure.
deephaven/deephaven-core pull request #4345
Opened 2023-08-19 02:28 UTC by jcferretti

Includes updating the cpp base docker image for the corresponding version that knows how to build
shared libraries for the dependencies (eg, gRPC and friends).

2023-08-19 20:51 UTC, kosak approved these changes

2023-08-20 21:59 UTC, kosak approved these changes

2023-08-20 22:04 UTC, kosak approved these changes

2023-08-21 14:13 UTC, alexpeters1208 approved these changes
LGTM

2023-08-21 15:22 UTC, chipkent requested changes

2023-08-21 15:22 UTC, chipkent commented on py/client-ticking/README.md
> +pip3 install --force --no-deps dist/pydeephaven_ticking-0.28.0-cp310-cp310-linux_x86_64.whl
This should have a note that the actual file name will vary based on the system being built on.

2023-08-21 15:33 UTC, devinrsmith submitted a review, later dismissed

2023-08-21 19:06 UTC, devinrsmith approved these changes

2023-08-21 19:07 UTC, kosak approved these changes

2023-08-21 20:27 UTC, chipkent approved these changes

2023-08-21 20:51 UTC, devinrsmith approved these changes

2023-08-21 20:51 UTC, merged