fix!: Update Iceberg snapshots table to use `Instant` timestamps.
deephaven/deephaven-core pull request #5865
Opened 2024-07-29 22:59 UTC by lbooker42

New snapshot table view:
<img width="1346" alt="image" src="https://github.com/user-attachments/assets/a4ff6984-cca5-4558-b1e1-a3bd488438a1">

2024-07-30 03:23 UTC, rcaudy requested changes

2024-07-30 03:23 UTC, rcaudy commented on extensions/iceberg/src/main/java/io/deephaven/iceberg/util/IcebergCatalogAdapter.java
> +        columnSourceMap.put("Timestamp", ReinterpretUtils.longToInstantSource(
This is a bit backwards. Make the `Instant` source initially, and then reinterpret it to long for filling purposes. The factories will even let you use a `long` array.

2024-07-30 03:24 UTC, rcaudy commented
> @devinrsmith I was also unsure. I imagine release notes are needed, but nothing in existing documentation will be affected.

It's a brand new feature, and I doubt anyone is using this programmatically. I would just break it.

2024-07-30 15:29 UTC, devinrsmith commented
It's not so much of a question of "should we break it"; it's more, should we "label" it a breaking change?

2024-07-31 19:04 UTC, rcaudy approved these changes

2024-08-01 00:44 UTC, merged