Update CONTRIBUTING.md
deephaven/deephaven-core pull request #6151
Opened 2024-09-29 09:18 UTC by margaretkennedy

Link to retitled guide

2024-09-29 09:25 UTC, margaretkennedy commented
Not sure which doc labels satisfy the check, as NoReleaseNotesNeeded and documentation don't seem to fit the bill.

2024-09-29 19:53 UTC, rcaudy requested changes

2024-09-29 19:53 UTC, rcaudy commented on CONTRIBUTING.md
> +For instructions on building and running, see [Build and launch from source code]([https://deephaven.io/core/docs/how-to-guides/launch-build/](https://deephaven.io/core/docs/getting-started/launch-bu
This doesn't look right as-is.
```suggestion
For instructions on building and running, see [Build and launch from source code](https://deephaven.io/core/docs/getting-started/launch-build/).
```

2024-09-30 19:34 UTC, chipkent approved these changes

2024-09-30 19:38 UTC, rcaudy approved these changes

2024-09-30 19:41 UTC, jjbrosnan commented
This broken link (along with others) were fixes as part of https://github.com/deephaven/deephaven-core/pull/6154.

There will be another PR in the coming days to add a tool to CI that will check for broken links regularly.

2024-09-30 19:41 UTC, closed without merging