feat: Format signature help when valid docstring style
deephaven/deephaven-core pull request #6170
Opened 2024-10-04 14:20 UTC by wusteven815

- Closes https://github.com/deephaven/web-client-ui/issues/2247
- Adds `docstring_parser` library for autocomplete usage
- If a valid docstring is found, format the autocomplete help tooltip with markdown, similar to how VS Code does it
- Regular docstrings can now use Markdown, but the whitespace style follows plain text

2024-10-04 16:53 UTC, devinrsmith requested changes

2024-10-04 16:53 UTC, devinrsmith commented on docker/server-jetty/src/main/server-jetty/requirements.txt
> +docstring_parser==0.16
Any new dependencies to the base images need to be made externally first: https://github.com/deephaven/deephaven-server-docker/blob/main/contexts/server-base/requirements.txt, and then an image bumping process to pull in the specific docker images. Feel free to reach out for more info.

2024-10-07 20:51 UTC, devinrsmith submitted a review, later dismissed

2024-10-07 20:51 UTC, devinrsmith commented on docker/server-jetty/src/main/server-jetty/requirements.txt
> +connectorx==0.3.3
The platform.machine spec needs to be manually added back on.

2024-10-07 20:51 UTC, devinrsmith commented on docker/server/src/main/server-netty/requirements.txt
> +connectorx==0.3.3
The platform.machine spec needs to be manually added back on.

2024-10-07 20:51 UTC, devinrsmith commented on py/server/setup.py
> +        "autocomplete": ["jedi==0.19.1", "docstring_parser==0.16"],
Like the base image, we should prefer to be more lenient. `>=0.16` is what I think you decided there.

2024-10-11 15:01 UTC, devinrsmith commented on docker/server-jetty/src/main/server-jetty/requirements.txt
> +docstring_parser>=0.16
*Almost*; this file is a "freeze", so it should include the exact dependencies. Sorry this stuff is not all automated...

2024-10-11 15:01 UTC, devinrsmith commented on docker/server/src/main/server-netty/requirements.txt
> +docstring_parser>=0.16
ditto

2024-12-19 19:43 UTC, devinrsmith reviewed
The totality of my review is/was around ensuring the base images contained the `docstring_parser` dependency and we are correctly depending on it from `py/server/setup.py`. In those regards, the PR is correct (the base image bumps already landed in main). I have not reviewed the other logic.

2025-01-08 23:00 UTC, chipkent commented on py/server/deephaven_internal/auto_completer/_signature_help.py
> +def _generate_description_markdown(docs: Docstring, params: list[Any]) -> str:
`params` typehint is too vague.  See comment on the return type above.

2025-01-08 23:08 UTC, chipkent commented on py/server/deephaven_internal/auto_completer/_signature_help.py
> +    ]
Should this be a class rather than a list in order to make it easier to work with?

2025-01-08 23:10 UTC, chipkent commented on py/server/deephaven_internal/auto_completer/_signature_help.py
> +def _get_signature_help(signature: Signature) -> list[Any]:
Should this have the `_` prefix removed since it is the method from the file that is used elsewhere?

2025-01-08 23:10 UTC, chipkent commented on py/server/deephaven_internal/auto_completer/_signature_help.py
> +def _get_signature_help(signature: Signature) -> list[Any]:
return signature is too vague.

2025-01-08 23:11 UTC, chipkent commented on py/server/deephaven_internal/auto_completer/_signature_help.py
> +        A list that contains [signature name, docstring, param docstrings, index]
Should this be returning something more structured/organized, like a class?

2025-02-14 15:55 UTC, mofojed commented on py/server/deephaven_internal/auto_completer/_signature_help.py
> +    ]
This is returned to Java, and was the format being done prior to this change. Was not looking to refactor it.

2025-02-14 18:58 UTC, mofojed commented
Closing in favour of https://github.com/deephaven/deephaven-core/pull/6649

2025-02-14 18:58 UTC, closed without merging