fix: JS subscriptions should return correct size while updating (#6463)
deephaven/deephaven-core pull request #6464
Opened 2024-12-06 02:03 UTC by niloc132

Fixes #6423

2024-12-06 15:38 UTC, mofojed submitted a review, later dismissed

2024-12-06 15:39 UTC, mofojed commented
Not sure what's up with the failing tests...

2024-12-06 20:02 UTC, mofojed commented
@niloc132 @dgodinez-dh found a new issue found with our e2e tests where our `Picker` components are no longer initializing with the default selected key correctly anymore, we think it may be related to this change. We want to investigate it a little bit more, find the root cause/resolution before this gets brought back to 0.37.x

2024-12-06 20:19 UTC, dgodinez-dh requested changes
We found an issue in deephaven.ui that we think is related to this change. Please wait to merge.

2024-12-10 15:07 UTC, dgodinez-dh approved these changes

2024-12-10 16:41 UTC, mofojed approved these changes

2024-12-10 21:45 UTC, merged