feat: Don't fail when reading non-identity partitioning columns
deephaven/deephaven-core pull request #6477
Opened 2024-12-10 20:12 UTC by malhotrashivam

Related to [DOC-230](https://deephaven.atlassian.net/browse/DOC-230)

2024-12-10 20:28 UTC, devinrsmith requested changes

2024-12-10 20:28 UTC, devinrsmith commented on extensions/iceberg/src/main/java/io/deephaven/iceberg/layout/IcebergKeyValuePartitionedLayout.java
> +                            icebergIndex.getAndIncrement());
This increment is not correct anymore because we now have a filter on the stream.

2024-12-10 20:28 UTC, devinrsmith commented on extensions/iceberg/src/main/java/io/deephaven/iceberg/layout/IcebergKeyValuePartitionedLayout.java
> +        identityPartitioningColumns = partitionSpec.fields().stream()
I think we should just do a for-loop instead with int index that is incremented...

2024-12-10 21:02 UTC, devinrsmith approved these changes

2024-12-10 22:42 UTC, devinrsmith approved these changes

2024-12-11 21:35 UTC, devinrsmith approved these changes

2024-12-11 22:29 UTC, merged

2024-12-11 22:29 UTC, deephaven-internal commented
Labels indicate documentation is required. Issues for documentation have been opened:

Community: https://github.com/deephaven/deephaven-docs-community/issues/368